### ISSUE TITLE
Can't start bot.

### ISSUE THREAD

**Issue by MistxOli** [skylerush/FortniteBot#5]
Whenever I try to start the bot I get this:

```
            fortnite.communicator.updateStatus(g_stt]);
                                               ^^^^^

SyntaxError: missing ) after argument list
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
```

**Comment by MistxOli** [comment]
bump

**Comment by Tipsymario3** [comment]
Bots are patched now with that method

**Comment by MistxOli** [comment]
Is there a new method now?

**Comment by Tipsymario3** [comment]
Yes but it can't do much and it's in java

**Comment by MistxOli** [comment]
Got a link to it please?

**Comment by MistxOli** [comment]
Can you send me a link to the Java bot?

**Comment by Tipsymario3** [comment]
https://github.com/Vrekt/Athena
